### ISSUE TITLE
Görüş

### ISSUE THREAD

**Issue by ahmetaliozdemir** [greencheap/greencheap#2]
Ellerinize sağlık , başlangıç için dökümantasyonlarınız çok iyi 
Yönetici paneli sade ve çok kullanışlı umarım emeğinizin karşılığını
güzel geri dönüşler ile almaya başlarsınız.

**Comment by ynswtf** [comment]
Teşekkür ederim, elimden geleni yapmaya çalışıyorum. Zamanım oldukça eklentiler ile geliştirmeye devam edeceğim.
