### ISSUE TITLE
Dashboard Bugs

### ISSUE THREAD

**Issue by yunus-emreee67** [greencheap/greencheap#3]
1.  Yoast'taki gibi anahtar kelime, site ismi ve açıklama yazılabilecek genel bir seo ayarı gerekli.
2.  Site bölümünde tema içeriği türkçeleştirilmesi gerek (standart tema).
3. Yönetim paneli sortable bug mevcut.
4.  İzinler ve roller bölümünde ki içerik türkçeleştirmesi gerek.
5.  İletişim formu gerek.
6.  Storage dosyaları taşıma işlemi.
7. Metin editörü üzerinde link ekleme esnasında başlık ve url yazıyorum. Başlık geliyor url bölümü boş geliyor.
@ynswtf

**Comment by ynswtf** [comment]
These requests will come resolved in greencheap version 3.
