### ISSUE TITLE
Yazım Ve Dil Hataları

### ISSUE THREAD

**Issue by yunus-emreee67** [greencheap/greencheap#6]
- kurulum yapılırken türkçe dil seçeneği seçilmiş fakat dashboard kısmında ve sayfada bazı yerler ingilizce olarak kalmış. örn: navbar, sayfalar ve hata mesajları
-  Güncelleme uyarısı verilen penceredeki butonda  güncelleme yazıyor `güncelle yazması gerekiyor`

**Comment by ynswtf** [comment]
These requests will come resolved in greencheap version 3.
